# Connect to Supabase via connection pooling
SUPABASE_URL="postgresql://postgres.eqrsiproaifukzxqitis:Lolybobb1$$$@aws-0-eu-west-1.pooler.supabase.com:6543/postgres?pgbouncer=true"

# Direct connection to the database. Used for migrations
SUPABASE_SERVICE_ROLE_KEY="postgresql://postgres.eqrsiproaifukzxqitis:Lolybobb1$$$@aws-0-eu-west-1.pooler.supabase.com:5432/postgres"

# .streamlit/secrets.toml
GEMINI_API_KEY = "AIzaSyDkjMi7ROthnGDQ4uYJmiDjNsrbs1XJIK0"
